Qoqo/Roqoqo Qiskit Devices
HQSquantumsimulations/qoqo-qiskit pull request #8
Opened 2023-05-24 16:26 UTC by mlodi-hqs

Two new packages containing Qoqo device interfaces for the following Qiskit's backends :
- Belem
- Jakarta
- Lagos
- Lima
- Manila
- Nairobi
- Perth
- Quito

`roqoqo_qiskit_devices` is a full Rust package, `qoqo_qiskit_devices` is the equivalent Python package built via pyo3.
The `device_property` module updates an ibm_device instance with gate times as well as decoherence information via the `qiskit_ibm_provider` package.

Also contains updates to `qoqo_qiskit`'s documentation.

2023-05-30 09:23 UTC, nfwvogt requested changes
Some smaller changes have been requested. Also besides the DEPENDENCIES file we should also have the LICENSE_FOR_BINARY_DISTRIBUTION and the Python license files added before we build and publish the wheels.

2023-05-30 09:23 UTC, nfwvogt commented on roqoqo_qiskit_devices/src/devices/ibm_belem.rs
> +        }
Here we should also add a check that only allows setting the gate time, if the edge is already in the device. So we can prevent the user adding 2qubit connections that are not really available on the physical hardware. This also goes for other devices.

2023-05-30 09:23 UTC, nfwvogt requested changes
Some smaller changes have been requested. Also besides the DEPENDENCIES file we should also have the LICENSE_FOR_BINARY_DISTRIBUTION and the Python license files added before we build and publish the wheels.

2023-05-31 09:02 UTC, mlodi-hqs commented on qoqo_qiskit_devices/docs/index.rst
> +   modules
Isn't it already that one? I don't see the difference with the structure of other packages.

2023-05-31 13:50 UTC, nfwvogt approved these changes
Looks good with one minor change

2023-05-31 13:50 UTC, nfwvogt commented on qoqo_qiskit_devices/qoqo_qiskit_devices/LICENSE_FOR_BINARY_DISTRIBUTION
> +This product in binary form links dynamically against Python  available under the Python license. For full license text see file qoqo_calculator_pyo3/PYTHON_LICENSE
Minor thing, we should replace `qoqo_calculator_pyo3` with `qoqo_qiskit_devices`

2023-05-31 14:22 UTC, merged